from syngenlib.data import GeneratorDataclass, GeneratorLossDataclass, TransformerDataclass, CapabilityModelDataclass
from syngenlib.data import GeneratorOperatingPoint, BranchOperatingPoint 
from syngenlib.models import GeneratorCalculationModel, SaturationBaseClass, LinearSaturationModel
from syngenlib.data import GeneratorBranchResults, CapabilityResults
 