from syngenlib.data import GeneratorDataClass, GeneratorOperatingPoint, GeneratorLossResult
from syngenlib.data import TransformerDataClass, TransformerLossResult, TransformerOperatingPoint
from syngenlib.data import CapabilityResult
from syngenlib.models import CapabilityDiagram, GeneratorLossModel, TransformerLossModel